if [ -f ~/.bashrc.inc ]; then
    source ~/.bashrc.inc
fi

export CLICOLOR=1
export EDITOR="vim"

## Bash completion scripts (requires "brew install bash-completion")
if [ -f /usr/local/bin/etc/bash_completion ]; then
    source /usr/local/bin/etc/bash_completion
fi

alias vi=vim

if [ -f /usr/local/etc/bash_completion.d/git-prompt.sh ]; then
    source /usr/local/etc/bash_completion.d/git-prompt.sh
    GIT_PS1_SHOWDIRTYSTATE=1
    GIT_PS1_SHOWSTASHSTATE=1
    GIT_PS1_SHOWUNTRACKEDFILES=1
    GIT_PS1_SHOWUPSTREAM="auto"
fi

if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then
    source /usr/local/bin/virtualenvwrapper.sh
fi

set_prompt () {
    local blue='\[\e[01;34m\]'
    local purple='\[\e[01;35m\]'
    local reset='\[\e[00m\]'
    # user@host
    PS1="\\u@\\h"
    # working directory in blue
    PS1+=": $blue\\w$reset"
    # git prompt
    PS1+="$purple$(__git_ps1 ' (%s)')$reset"
    # ending prompt
    PS1+='\n\\$ '
}

PROMPT_COMMAND='set_prompt'
